### ISSUE TITLE
create a shell script on arrays

### ISSUE THREAD

**Issue by companyabab** [vunnava123/Develop#7]
Hi Samba,

Hope you are doing good.

lets start a new task on creating array  and special charecters.

Regards
Company.ABAB

**Comment by vunnava123** [comment]
#!/bin/sh

NAME[0]="samba"
NAME[1]="siva"
NAME[2]="vunnava"
NAME[3]="Ayan"
NAME[4]="rao"
echo "First Method: ${NAME[*]}"
echo "Second Method: ${NAME[@]}"

**Comment by companyabab** [comment]
i am impressed but confused .
